{% set name = "nx-parallel" %}
{% set version = "0.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/nx_parallel-{{ version }}.tar.gz
  sha256: c1098436b440815cb4246e5592db9cc60dc9c912ead22289a0586afff0c39db7

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.10
    - hatchling
    - pip
  run:
    - python >=3.10
    - networkx
    - joblib

test:
  imports:
    - nx_parallel
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/networkx/nx-parallel
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.md
  summary: "A parallel backend for NetworkX"
  description: |
    A parallel backend for NetworkX. It uses joblib to run NetworkX algorithms
    on multiple CPU cores.
  doc_url: https://github.com/networkx/nx-parallel
  dev_url: https://github.com/networkx/nx-parallel

extra:
  recipe-maintainers:
    - MridulS
    - Schefflera-Arboricola
